version: '3'
services:
    postgres:
        image: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
            - POSTGRES_DATABASE=bidsys
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql